#default local
spring:
  profiles:
    active: local
server:
  port: 8090
app:
  client:
    id: id
    secret: secret
auth:
  server:
    schem: http
host:
  full:
    dns:
      auth:
        link: http://localhost/oauth/token:8090

#local
---
spring:
  profiles: local
  datasource:
    url: jdbc:h2:mem:capstone
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
#prod
---
spring:
  profiles: prod
  include: real-db
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
#spring.jpa.properties.hibernate.format_sql=true
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

